/**
 * End-to-end acceptance: a real MCP client speaks stdio to the
 * BUILT dist/cli.js, which speaks HTTP to the simulator — the full
 * upload → reconstruct → query → agent → export → artifact flow.
 * The run is recorded to examples/transcript.md (the recorded demo transcript).
 */
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import {
  StdioClientTransport,
  getDefaultEnvironment,
} from '@modelcontextprotocol/sdk/client/stdio.js';
import { REST_PATHS } from '@reality/protocol';
import { startSimulator, type RunningSimulator } from '../simulator/sim.js';
import { FIXTURE_RUN_ID, FIXTURE_SCAN_ID } from '../simulator/fixture.js';

const pkgDir = dirname(dirname(fileURLToPath(import.meta.url)));
const cliPath = join(pkgDir, 'dist', 'cli.js');

let sim: RunningSimulator;
let client: Client;
let workDir: string;
let artifactsDir: string;

interface TranscriptStep {
  title: string;
  tool: string;
  args: Record<string, unknown>;
  result: string;
}
const transcript: TranscriptStep[] = [];

async function call(
  title: string,
  tool: string,
  args: Record<string, unknown>,
): Promise<{ text: string; parsed: any; isError: boolean; images: number }> {
  const res = (await client.callTool({ name: tool, arguments: args })) as {
    content: Array<{ type: string; text?: string; data?: string }>;
    isError?: boolean;
  };
  const text = res.content
    .filter((c) => c.type === 'text')
    .map((c) => c.text)
    .join('\n');
  const images = res.content.filter((c) => c.type === 'image').length;
  let parsed: any = null;
  try {
    parsed = JSON.parse(text);
  } catch {
    parsed = null;
  }
  transcript.push({
    title,
    tool,
    args,
    result:
      (res.isError ? '[ERROR] ' : '') +
      (images ? `[${images} image] ` : '') +
      (text.length > 900 ? text.slice(0, 900) + ' …' : text),
  });
  return { text, parsed, isError: !!res.isError, images };
}

beforeAll(async () => {
  expect(existsSync(cliPath), 'dist/cli.js must exist — npm test builds first').toBe(true);
  sim = await startSimulator({ port: 0 });
  workDir = mkdtempSync(join(tmpdir(), 'orl-e2e-'));
  artifactsDir = join(workDir, 'artifacts');
  client = new Client({ name: 'e2e-harness', version: '0.0.0' });
  const transport = new StdioClientTransport({
    command: process.execPath,
    args: [cliPath, 'serve'],
    env: {
      ...getDefaultEnvironment(),
      OPENREALITY_URL: sim.url,
      OPENREALITY_TOKEN: 'e2e-token',
      OPENREALITY_DIR: join(workDir, 'config'),
      OPENREALITY_ARTIFACTS_DIR: artifactsDir,
    },
  });
  await client.connect(transport);
});

afterAll(async () => {
  // the demo transcript is a repo deliverable — always write it
  const lines: string[] = [
    '# openreality-mcp demo transcript',
    '',
    'A real MCP client driving the built `openreality-mcp` server over stdio against the',
    'mock-backend simulator (`openreality-mcp simulator`): scan upload → reconstruction job →',
    'scene sync → measurement (relative → anchored metres) → agent chat/replay → export →',
    'artifact fetch. Regenerated by `npm test` (test/e2e.test.ts).',
    '',
  ];
  for (const [i, step] of transcript.entries()) {
    lines.push(`## ${i + 1}. ${step.title}`);
    lines.push('');
    lines.push('```json');
    lines.push(`→ ${step.tool} ${JSON.stringify(step.args)}`);
    lines.push('```');
    lines.push('');
    lines.push('```');
    lines.push(step.result || '(empty)');
    lines.push('```');
    lines.push('');
  }
  mkdirSync(join(pkgDir, 'examples'), { recursive: true });
  writeFileSync(join(pkgDir, 'examples', 'transcript.md'), lines.join('\n'));
  await client?.close();
  await sim?.close();
});

describe('scan-to-artifact flow over MCP', () => {
  let scanId: string;

  it('exposes the full tool surface and the scene resources', async () => {
    const tools = await client.listTools();
    const names = tools.tools.map((t) => t.name);
    for (const required of [
      'workspace_list_scenes',
      'workspace_upload_video',
      'workspace_upload_recording',
      'workspace_upload_splat',
      'workspace_job_wait',
      'scene_card',
      'scene_list_objects',
      'scene_measure_distance',
      'scene_measure_angle',
      'scene_plan_path',
      'scene_planes',
      'scene_ground_frame',
      'scene_anchor',
      'scene_keyframe_image',
      'scene_lod',
      'scene_segment',
      'scene_object_complete',
      'agent_annotate',
      'agent_chat',
      'agent_replay',
      'agent_runs',
      'agent_run_events',
      'export_manifest',
      'export_prepare',
      'export_status',
      'artifact_fetch',
      'artifact_fetch_splat',
      'scene_share',
    ]) {
      expect(names, `missing tool ${required}`).toContain(required);
    }
    expect(names.length).toBeGreaterThanOrEqual(28);

    const resources = await client.listResources();
    expect(resources.resources.map((r) => r.uri)).toContain('openreality://scenes');
    const index = await client.readResource({ uri: 'openreality://scenes' });
    expect(String((index.contents[0] as { text?: string }).text)).toContain(FIXTURE_SCAN_ID);
  });

  it('uploads a video and waits the recon job to done', async () => {
    const video = join(workDir, 'kitchen.mp4');
    writeFileSync(video, Buffer.from('not-actually-mp4-but-the-sim-does-not-decode'));
    const up = await call('Upload a capture video', 'workspace_upload_video', {
      path: video,
      label: 'Kitchen walkthrough',
    });
    expect(up.isError).toBe(false);
    expect(up.parsed.job_id).toBeTruthy();
    scanId = up.parsed.scan_id;

    const wait = await call('Wait for the reconstruction job', 'workspace_job_wait', {
      job_id: up.parsed.job_id,
      timeout_s: 30,
      poll_s: 0.05,
    });
    expect(wait.parsed.final.status).toBe('done');
    expect(wait.parsed.trail.join(' ')).toContain('recon');
  });

  it('syncs the account and sees the new scene', async () => {
    const list = await call('Sync the account (list scenes)', 'workspace_list_scenes', {});
    expect(list.parsed.scenes.map((s: { scan_id: string }) => s.scan_id)).toContain(scanId);
    expect(list.parsed.new_since_last_sync).toContain(scanId);
  });

  it('renders the context card (un-anchored honesty)', async () => {
    const card = await call('Scene context card', 'scene_card', { scan_id: scanId });
    expect(card.text).toContain('un-anchored');
    expect(card.text).toContain('RELATIVE');
  });

  it('measures in relative units before the anchor', async () => {
    const m = await call('Measure desk→chair (pre-anchor)', 'scene_measure_distance', {
      scan_id: scanId,
      point_a: [0, 0, 0],
      point_b: [1, 0, 0],
    });
    expect(m.parsed.units).toBe('relative');
    expect(m.parsed.scale_source).toBe('none');
  });

  it('refuses the Isaac export while un-anchored (metric gate)', async () => {
    const man = await call('Isaac export manifest (pre-anchor)', 'export_manifest', {
      scan_id: scanId,
      format: 'isaac_usd',
    });
    expect(man.parsed.zip_available).toBe(false);
    expect(man.parsed.zip_blocked_reason).toMatch(/metric_gate/);
  });

  it('anchors the scene and measures in metres', async () => {
    const anchor = await call('Anchor: 1 SLAM unit = 2 m', 'scene_anchor', {
      scan_id: scanId,
      point_a: [0, 0, 0],
      point_b: [1, 0, 0],
      distance_m: 2.0,
      materialize: 'job',
    });
    expect(anchor.parsed.pending).toBe(true);
    const wait = await call('Wait for anchor materialization', 'workspace_job_wait', {
      job_id: anchor.parsed.job_id,
      timeout_s: 30,
      poll_s: 0.05,
    });
    expect(wait.parsed.final.status).toBe('done');

    const m = await call('Measure again (post-anchor)', 'scene_measure_distance', {
      scan_id: scanId,
      point_a: [0, 0, 0],
      point_b: [1, 0, 0],
    });
    expect(m.parsed.units).toBe('m');
    expect(m.parsed.value).toBeCloseTo(2.0, 6);
    expect(m.parsed.scale_source).toMatch(/^anchor:/);
  });

  it('lists objects and plans a path to one', async () => {
    const objs = await call('List scene objects', 'scene_list_objects', { scan_id: scanId });
    expect(objs.parsed.closed_world).toBe(true);
    expect(objs.parsed.count).toBeGreaterThan(0);

    const plan = await call('Plan a path to object det:1', 'scene_plan_path', {
      scan_id: scanId,
      object_uid: 'det:1',
    });
    expect(plan.parsed.provenance).toMatch(/not certified navigation/);
    expect(plan.parsed.waypoints_world.length).toBeGreaterThan(2);
    expect(plan.parsed.units).toBe('m');
  });

  it('keeps the pose flythrough out of context and says so', async () => {
    const plan = await call('Plan a path to object det:1', 'scene_plan_path', {
      scan_id: scanId,
      object_uid: 'det:1',
    });
    // The trajectory is artifact-shaped: poses stay on disk, waypoints come back as a
    // preview, and both the true counts and the fetch route ride along.
    expect(plan.parsed.poses).toBeUndefined();
    expect(plan.parsed.poses_omitted.n_poses).toBe(41);
    expect(plan.parsed.poses_omitted.fetch).toMatch(/^derived\/demo\/nav\/paths\//);
    expect(plan.parsed.waypoints_total).toBe(41);
    expect(plan.parsed.waypoints_world).toHaveLength(24);
    expect(plan.parsed.waypoints_truncated).toBe(true);
    expect(plan.parsed.waypoints_note).toMatch(/24 of 41/);
    // Sampling keeps the endpoints, so the path still starts and ends where it planned to.
    const full = await call('Plan a path with the full trajectory', 'scene_plan_path', {
      scan_id: scanId,
      object_uid: 'det:1',
      include_poses: true,
      max_waypoints: 2000,
    });
    expect(full.parsed.poses).toHaveLength(41);
    expect(full.parsed.waypoints_truncated).toBeUndefined();
    expect(plan.parsed.waypoints_world[0]).toEqual(full.parsed.waypoints_world[0]);
    expect(plan.parsed.waypoints_world[23]).toEqual(full.parsed.waypoints_world[40]);
    // The honesty fields survive the trim.
    expect(plan.parsed.units).toBe(full.parsed.units);
    expect(plan.parsed.units_basis).toBe(full.parsed.units_basis);
    expect(plan.parsed.stats.n_frames).toBe(41);
  });

  it('reads planes + ground frame', async () => {
    const planes = await call('Detect planes', 'scene_planes', { scan_id: scanId });
    expect(planes.parsed.planes.length).toBeGreaterThanOrEqual(2);
    const gf = await call('Ground frame', 'scene_ground_frame', { scan_id: scanId });
    expect(gf.parsed.frame.vertical_axis_known).toBe(true);
  });

  it('chats with the scene agent and reads the transcript', async () => {
    const chat = await call('Agent chat: what is in this room?', 'agent_chat', {
      scan_id: scanId,
      message: 'What is in this room, and how big is it?',
      timeout_s: 30,
      poll_s: 0.05,
    });
    expect(chat.text).toContain('status: done');
    expect(chat.text).toContain('closed-world objects');
    expect(chat.text).toContain('run done');

    const runs = await call('List agent runs', 'agent_runs', { scan_id: scanId });
    expect(runs.parsed.runs.length).toBeGreaterThanOrEqual(1);
    expect(runs.parsed.active_run_id).toBeNull();
  });

  it('replays the fixture run for $0', async () => {
    const replay = await call('Replay the recorded annotate run', 'agent_replay', {
      scan_id: FIXTURE_SCAN_ID,
      source_run_id: FIXTURE_RUN_ID,
    });
    expect(replay.parsed.replay).toBe(true);
    const drained = await call('Drain the replay events', 'agent_run_events', {
      scan_id: FIXTURE_SCAN_ID,
      run_id: replay.parsed.run_id,
      wait_for_done: true,
      timeout_s: 30,
      poll_s: 0.05,
    });
    expect(drained.text).toContain('status: done');
  });

  it('fetches a keyframe as an image', async () => {
    const kf = await call('Fetch fixture keyframe', 'scene_keyframe_image', {
      scan_id: FIXTURE_SCAN_ID,
      blob_key: 'kf_0_4.png',
    });
    expect(kf.images).toBe(1);
  });

  it('builds + downloads the openreality export (bytes to disk, never context)', async () => {
    const prep = await call('Prepare the openreality export', 'export_prepare', {
      scan_id: scanId,
      format: 'openreality',
      timeout_s: 30,
      poll_s: 0.05,
    });
    expect(prep.parsed.prepared.status).toBe('ready');
    const key = prep.parsed.prepared.artifact.key;

    const fetched = await call('Fetch the export zip to disk', 'artifact_fetch', {
      scan_id: scanId,
      derived_key: key,
    });
    expect(fetched.parsed.path).toContain(artifactsDir);
    const bytes = readFileSync(fetched.parsed.path);
    expect(bytes.subarray(0, 2).toString('latin1')).toBe('PK'); // a real zip
    expect(bytes.byteLength).toBe(fetched.parsed.bytes);
  });

  it('fetches the splat to disk and mints a share link', async () => {
    const splat = await call('Fetch splat.ply to disk', 'artifact_fetch_splat', {
      scan_id: FIXTURE_SCAN_ID,
    });
    expect(readFileSync(splat.parsed.path, 'utf8')).toContain('ply');

    const share = await call('Mint a read-only share link', 'scene_share', {
      scan_id: FIXTURE_SCAN_ID,
    });
    expect(share.parsed.embed_url).toContain('share_token');
  });

  it('surfaces server refusals as structured tool errors (409 agent_run_active)', async () => {
    const first = await call('Start an annotate run', 'agent_annotate', { scan_id: scanId });
    expect(first.parsed.run_id).toBeTruthy();
    const second = await call('Start a second run (expect 409)', 'agent_annotate', {
      scan_id: scanId,
    });
    expect(second.isError).toBe(true);
    expect(second.parsed.http_status).toBe(409);
    expect(second.parsed.body.error).toBe('agent_run_active');
    // drain so the sim ends clean
    await call('Drain the annotate run', 'agent_run_events', {
      scan_id: scanId,
      run_id: first.parsed.run_id,
      wait_for_done: true,
      timeout_s: 30,
      poll_s: 0.05,
    });
  });
});

describe('durable API key (ork_) credential over MCP', () => {
  it('authenticates tool calls with a minted ork_ key, and once revoked surfaces a clear, non-looping error', async () => {
    const mint = await fetch(sim.url + REST_PATHS.API_KEYS, {
      method: 'POST',
      headers: { Authorization: 'Bearer e2e-token', 'Content-Type': 'application/json' },
      body: JSON.stringify({ name: 'e2e-key' }),
    });
    expect(mint.status).toBe(200);
    const minted = (await mint.json()) as { key: string; key_id: string };
    expect(minted.key.startsWith('ork_')).toBe(true);

    const keyWorkDir = mkdtempSync(join(tmpdir(), 'orl-e2e-key-'));
    const keyClient = new Client({ name: 'e2e-key-harness', version: '0.0.0' });
    const keyTransport = new StdioClientTransport({
      command: process.execPath,
      args: [cliPath, 'serve'],
      env: {
        ...getDefaultEnvironment(),
        OPENREALITY_URL: sim.url,
        OPENREALITY_TOKEN: minted.key,
        OPENREALITY_DIR: join(keyWorkDir, 'config'),
        OPENREALITY_ARTIFACTS_DIR: join(keyWorkDir, 'artifacts'),
      },
    });
    await keyClient.connect(keyTransport);
    try {
      const list = (await keyClient.callTool({ name: 'workspace_list_scenes', arguments: {} })) as {
        content: Array<{ type: string; text?: string }>;
        isError?: boolean;
      };
      expect(list.isError).toBeFalsy();

      await fetch(sim.url + REST_PATHS.API_KEY(minted.key_id), {
        method: 'DELETE',
        headers: { Authorization: 'Bearer e2e-token' },
      });

      const start = Date.now();
      const after = (await keyClient.callTool({ name: 'workspace_list_scenes', arguments: {} })) as {
        content: Array<{ type: string; text?: string }>;
        isError?: boolean;
      };
      expect(Date.now() - start).toBeLessThan(5_000); // answered promptly — no refresh-retry loop
      expect(after.isError).toBe(true);
      const text = after.content
        .filter((c) => c.type === 'text')
        .map((c) => c.text)
        .join('\n');
      expect(text).toMatch(/revoked/i);
      expect(text).toMatch(/login/i);
    } finally {
      await keyClient.close();
    }
  });
});
