#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

usage() {
  cat <<'EOF'
usage: ./render.sh <agent> <background> [t_cloud t_measure t_metric t_export [panel options...]]

  agent        codex | claude | cursor      which AI assistant drives the take
  background   green | black | grey | all   terminal background (all = the three, one after another)

Without the four times the output is the terminal alone:
  out/<agent>-<background>.mp4 and out/<agent>-<background>.gif
With the four times (seconds at which the take reaches each scene beat) the
synchronized scene panel is rendered and composited beside the terminal too:
  out/<agent>-<background>-scene.mp4 and out/<agent>-<background>-scene.gif
Anything after the four times goes to render_scene_panel.py (for example an
actual --splat and its measured endpoints; see README.md).

Environment: DEMO_PORT (default 8973), DEMO_WORKSPACE (default
/Users/Shared/openreality-demo, else /tmp/openreality-demo: no user name on camera),
DEMO_MODEL (claude: opus; cursor: the account default; ignored for codex),
DEMO_DRY_RUN=1 (write build/<agent>-<background>.tape and stop),
DEMO_SKIP_RECORD=1 (reuse an existing out/<agent>-<background>.mp4 and only
render the scene panel; this is how to iterate on the four beat times).
EOF
}

if [ "$#" -lt 2 ]; then
  usage
  exit 2
fi

AGENT="$1"
BG="$2"
shift 2

case "$AGENT" in
  codex|claude|cursor) ;;
  *) echo "unknown agent: $AGENT"; usage; exit 2 ;;
esac

if [ "$BG" = "all" ]; then
  for one in green black grey; do
    "$0" "$AGENT" "$one" "$@"
  done
  exit 0
fi

case "$BG" in
  green|black|grey) ;;
  *) echo "unknown background: $BG"; usage; exit 2 ;;
esac

if [ "$#" -ne 0 ] && [ "$#" -lt 4 ]; then
  usage
  exit 2
fi

export DEMO_AGENT="$AGENT"
export DEMO_PORT="${DEMO_PORT:-8973}"
if [ -z "${DEMO_WORKSPACE:-}" ]; then
  # Same default as setup.sh: a folder whose path shows no user name.
  if [ -d /Users/Shared ] && [ -w /Users/Shared ]; then
    DEMO_WORKSPACE=/Users/Shared/openreality-demo
  else
    DEMO_WORKSPACE=/tmp/openreality-demo
  fi
fi
export DEMO_WORKSPACE
case "$AGENT" in
  claude) export DEMO_MODEL="${DEMO_MODEL:-opus}" ;;
  *) export DEMO_MODEL="${DEMO_MODEL:-}" ;;
esac

case "$AGENT" in
  codex) AGENT_CLI=codex ;;
  claude) AGENT_CLI=claude ;;
  cursor) AGENT_CLI=cursor-agent ;;
esac
for tool in vhs ttyd ffmpeg ffprobe "$AGENT_CLI"; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "missing required command: $tool"
    exit 1
  fi
done

# Brand palette (docs/assets/hero.svg): deep green #0b3d2c, gold #d4a017,
# coral #e07070. Only the background family changes between variants.
bg_hex() {
  case "$1" in
    green) echo "#071c15" ;;
    black) echo "#000000" ;;
    grey)  echo "#1a1a1a" ;;
  esac
}

theme_json() {
  local bg black bright sel
  case "$1" in
    green) bg="#071c15"; black="#0b3d2c"; bright="#3a5c4c"; sel="#0b3d2c" ;;
    black) bg="#000000"; black="#1c1c1c"; bright="#5c5c5c"; sel="#262626" ;;
    grey)  bg="#1a1a1a"; black="#2b2b2b"; bright="#6b6b6b"; sel="#333333" ;;
  esac
  printf '{ "name": "openreality-%s", "background": "%s", "foreground": "#e8e3d5", "cursor": "#d4a017", "selection": "%s", "black": "%s", "red": "#e07070", "green": "#3fa06f", "yellow": "#d4a017", "blue": "#7fa8c9", "magenta": "#b48ead", "cyan": "#7fc7bd", "white": "#e8e3d5", "brightBlack": "%s", "brightRed": "#f0a0a0", "brightGreen": "#66c294", "brightYellow": "#f0c75e", "brightBlue": "#a3c6e0", "brightMagenta": "#d0b8d8", "brightCyan": "#a5ded6", "brightWhite": "#ffffff" }' \
    "$1" "$bg" "$sel" "$black" "$bright"
}

# The per-agent tapes in tapes/ carry the beats; this header carries what
# varies per take (outputs, theme, model flag). DEMO_* reach setup.sh through
# the environment: a VHS `Env` line would work too, but VHS then ignores every
# `Set` that follows it (Height, PlaybackSpeed), so none is written.
MODEL_FLAG=""
if [ -n "$DEMO_MODEL" ]; then
  MODEL_FLAG="--model $DEMO_MODEL "
fi
mkdir -p build out
TAPE="build/$AGENT-$BG.tape"
{
  echo "# generated by render.sh from tapes/$AGENT.tape; edit that file instead"
  echo "Output out/$AGENT-$BG.mp4"
  echo "Output out/$AGENT-$BG.gif"
  echo "Set Theme $(theme_json "$BG")"
  grep -v -E '^(Output|Set Theme) ' "tapes/$AGENT.tape" \
    | sed -e "s|@MODEL_FLAG@|$MODEL_FLAG|g" -e "s|@PORT@|$DEMO_PORT|g"
} > "$TAPE"

cleanup() {
  case "$AGENT" in
    codex) codex mcp remove openreality-demo >/dev/null 2>&1 || true ;;
    claude) ;;  # the take's server lives in the workspace's .mcp.json, deleted below
    cursor) ;;
  esac
  if [ -f "$DEMO_WORKSPACE/sim.pid" ]; then
    DEMO_PID=$(sed -n '1p' "$DEMO_WORKSPACE/sim.pid")
    case "$DEMO_PID" in
      ''|*[!0-9]*) ;;
      *) kill "$DEMO_PID" >/dev/null 2>&1 || true ;;
    esac
  fi
  if [ -e "$DEMO_WORKSPACE/.openreality-demo-workspace" ]; then
    rm -rf "$DEMO_WORKSPACE"
  fi
}
trap cleanup EXIT INT TERM

if [ -n "${DEMO_DRY_RUN:-}" ]; then
  trap - EXIT INT TERM
  echo "dry run: wrote $TAPE"
  exit 0
fi

if [ -n "${DEMO_SKIP_RECORD:-}" ] && [ -f "out/$AGENT-$BG.mp4" ]; then
  trap - EXIT INT TERM
  echo "reusing out/$AGENT-$BG.mp4 (DEMO_SKIP_RECORD is set)"
else
  echo "recording $AGENT on $BG -> out/$AGENT-$BG.mp4"
  vhs "$TAPE"
fi

if [ "$#" -eq 0 ]; then
  echo "wrote out/$AGENT-$BG.mp4 and out/$AGENT-$BG.gif"
  exit 0
fi

T_CLOUD="$1"; T_MEASURE="$2"; T_METRIC="$3"; T_EXPORT="$4"
shift 4

TERMINAL="out/$AGENT-$BG.mp4"
TERMINAL_DURATION=$(ffprobe -v error -show_entries format=duration -of default=nw=1:nk=1 "$TERMINAL")

if python3 -c 'import numpy, matplotlib' >/dev/null 2>&1; then
  RENDER_PYTHON=(python3)
elif command -v uv >/dev/null 2>&1; then
  RENDER_PYTHON=(uv --cache-dir /tmp/openreality-demo-uv-cache run --isolated --with "numpy<2" --with "matplotlib>=3.8" python)
else
  echo 'rendering requires compatible NumPy + Matplotlib; see docs/demo/README.md'
  exit 1
fi

"${RENDER_PYTHON[@]}" render_scene_panel.py \
  --duration "$TERMINAL_DURATION" \
  --bg "$(bg_hex "$BG")" \
  --t-cloud "$T_CLOUD" \
  --t-measure "$T_MEASURE" \
  --t-metric "$T_METRIC" \
  --t-export "$T_EXPORT" \
  --terminal "$TERMINAL" \
  --out "build/$AGENT-$BG-panel.mp4" \
  --composite "out/$AGENT-$BG-scene.mp4" \
  "$@"

# The rotating point cloud changes every pixel of the right half each frame,
# so the GIF is kept to 8 fps, 1120 px wide and 80 colours without dithering
# to land under 10 MB (GitHub's practical README limit).
ffmpeg -y -v error -i "out/$AGENT-$BG-scene.mp4" \
  -vf "fps=8,scale=1120:-2:flags=lanczos,split[a][b];[a]palettegen=stats_mode=diff:max_colors=80[p];[b][p]paletteuse=dither=none:diff_mode=rectangle" \
  -loop 0 "out/$AGENT-$BG-scene.gif"

echo "wrote out/$AGENT-$BG.mp4, out/$AGENT-$BG.gif, out/$AGENT-$BG-scene.mp4 and out/$AGENT-$BG-scene.gif"
