"""SPZ decoder tests — verified against ground truth produced by Spark itself.

The fixtures in ``tests/fixtures/spz/`` were generated by driving the **encoder we
ship**, ``@sparkjsdev/spark`` 0.1.10's ``SpzWriter`` (in
``web/apps/webserver/node_modules/@sparkjsdev/spark/dist/spark.module.js``), from
node with known inputs:

    truth_sh3.spz  128 gaussians, SH degree 3, v3 container, fractionalBits 12
    truth_sh0.spz   96 gaussians, SH degree 0, v3 container, fractionalBits 12

Each ``.spz`` has a sibling ``.npz`` holding the exact values fed to the encoder
(``f_rest`` already re-ordered into PLY channel-major order). So these tests are
not "does the decoder agree with itself" — they assert that ``server.oreos.spz``
recovers what the reference implementation encoded, to within each field's
documented quantization step. That is the guard that lets us accept ``.spz``
uploads at all.

Tolerances below are derived, not tuned:
  centre  1/(2 * 2**fractionalBits)          fixed-point half-step
  colour  0.5/255 * (SH_C0/0.15)             8-bit over the SPZ colour range
  alpha   0.5/255                            8-bit
  scale   exp(1/32) - 1                      8-bit over log scale, relative
  quat    (1/sqrt2)/511                      9-bit smallest-three
  sh      bucket/128                         quantizeSh floors onto bucket
                                             multiples (8 for deg-1, 16 for deg-2+)
"""

from __future__ import annotations

import os

import numpy as np
import pytest

from server.oreos.spz import SpzError, decode_spz, read_spz_header, spz_to_ply_file

FIXTURES = os.path.join(os.path.dirname(__file__), "fixtures", "spz")

SH_C0 = 0.28209479177387814
TOL_CENTER = 0.5 / 4096
TOL_COLOR = 0.5 / 255 * (SH_C0 / 0.15)
TOL_ALPHA = 0.5 / 255
TOL_SCALE_REL = np.exp(1 / 32) - 1
TOL_QUAT = (1 / np.sqrt(2)) / 511


def _truth(name: str):
    return np.load(os.path.join(FIXTURES, f"{name}.npz"))


@pytest.mark.parametrize("name,n,degree", [("truth_sh3", 128, 3), ("truth_sh0", 96, 0)])
def test_header_matches_encoder(name, n, degree):
    header = read_spz_header(os.path.join(FIXTURES, f"{name}.spz"))
    assert header.version == 3
    assert header.num_splats == n
    assert header.sh_degree == degree
    assert header.fractional_bits == 12
    assert header.antialiased is True


@pytest.mark.parametrize("name", ["truth_sh3", "truth_sh0"])
def test_decode_recovers_encoder_inputs(name):
    """Every field round-trips within its own quantization step."""
    truth = _truth(name)
    fields = decode_spz(os.path.join(FIXTURES, f"{name}.spz"))

    centers = np.stack([fields["x"], fields["y"], fields["z"]], axis=1)
    assert np.abs(centers - truth["centers"]).max() <= TOL_CENTER

    color = 0.5 + SH_C0 * np.stack([fields[f"f_dc_{i}"] for i in range(3)], axis=1)
    assert np.abs(color - truth["rgbs"]).max() <= TOL_COLOR

    alpha = 1.0 / (1.0 + np.exp(-fields["opacity"]))
    assert np.abs(alpha - truth["alphas"]).max() <= TOL_ALPHA

    scale = np.exp(np.stack([fields[f"scale_{i}"] for i in range(3)], axis=1))
    assert np.abs(scale / truth["scales"] - 1.0).max() <= TOL_SCALE_REL

    # PLY stores (w, x, y, z); the fixture stores (x, y, z, w). q and -q are the
    # same rotation, so compare up to sign.
    quat = np.stack([fields["rot_1"], fields["rot_2"], fields["rot_3"], fields["rot_0"]], axis=1)
    sign = np.sign((quat * truth["quats"]).sum(axis=1))[:, None]
    assert np.abs(quat * sign - truth["quats"]).max() <= TOL_QUAT * 1.05


def test_decode_sh_channel_major_order():
    """f_rest_* must come out channel-major (all R coefficients, then G, then B)
    — Spark's PLY reader indexes them as ``k + d * coeffs_per_channel``, and
    getting this backwards silently ruins view-dependent colour."""
    truth = _truth("truth_sh3")
    fields = decode_spz(os.path.join(FIXTURES, "truth_sh3.spz"))
    coeffs = 15  # degree 3
    got = np.stack([fields[f"f_rest_{j}"] for j in range(3 * coeffs)], axis=1)
    expected = truth["f_rest"]
    # degree-1 block quantizes onto multiples of 8/255-ish buckets, degree-2+ of 16.
    deg1 = [d * coeffs + k for d in range(3) for k in range(3)]
    rest = [d * coeffs + k for d in range(3) for k in range(3, coeffs)]
    assert np.abs(got[:, deg1] - expected[:, deg1]).max() <= 8.0 / 128
    assert np.abs(got[:, rest] - expected[:, rest]).max() <= 16.0 / 128


def test_decoded_field_set_is_a_valid_3dgs_schema():
    fields = decode_spz(os.path.join(FIXTURES, "truth_sh3.spz"))
    assert len(fields) == 62  # 17 base + 45 f_rest (degree 3)
    for required in ("x", "y", "z", "f_dc_0", "opacity", "scale_0", "rot_0"):
        assert required in fields
    names = list(fields)
    assert names[:9] == ["x", "y", "z", "nx", "ny", "nz", "f_dc_0", "f_dc_1", "f_dc_2"]
    assert names[-8:] == ["opacity", "scale_0", "scale_1", "scale_2",
                          "rot_0", "rot_1", "rot_2", "rot_3"]
    assert all(v.dtype == np.float32 and v.shape == (128,) for v in fields.values())


def test_spz_to_ply_file_roundtrips_through_splat_io(tmp_path):
    """The converted .ply must read back through the reader the import path uses."""
    from server.scene_report.splat_io import read_splat_ply

    out = tmp_path / "converted.ply"
    info = spz_to_ply_file(os.path.join(FIXTURES, "truth_sh3.spz"), str(out))
    assert info == {"gaussian_count": 128, "sh_degree": 3, "version": 3}

    fields = read_splat_ply(str(out))
    assert len(fields) == 62
    direct = decode_spz(os.path.join(FIXTURES, "truth_sh3.spz"))
    for name, value in direct.items():
        np.testing.assert_allclose(fields[name], value, rtol=0, atol=0)


def test_gaussian_cap_checked_before_decode():
    with pytest.raises(SpzError) as exc:
        decode_spz(os.path.join(FIXTURES, "truth_sh3.spz"), max_gaussians=10)
    assert "over the 10 import limit" in str(exc.value)


def test_not_gzip_is_honest(tmp_path):
    bad = tmp_path / "plain.spz"
    bad.write_bytes(b"ply\nformat binary_little_endian 1.0\n")
    with pytest.raises(SpzError) as exc:
        read_spz_header(str(bad))
    assert "SPZ container" in str(exc.value)


def test_bad_magic_is_honest(tmp_path):
    import gzip

    bad = tmp_path / "wrong.spz"
    bad.write_bytes(gzip.compress(b"\x00" * 32))
    with pytest.raises(SpzError) as exc:
        read_spz_header(str(bad))
    assert "not an SPZ file" in str(exc.value)


def test_truncated_body_is_honest(tmp_path):
    import gzip
    import struct

    header = struct.pack("<IIIBBBB", 0x5053474E, 3, 5000, 0, 12, 1, 0)
    bad = tmp_path / "short.spz"
    bad.write_bytes(gzip.compress(header + b"\x00" * 64))
    with pytest.raises(SpzError) as exc:
        decode_spz(str(bad))
    assert "truncated" in str(exc.value)
